platform :ios, '6.0'
xcodeproj 'fanto/fanto.xcodeproj'

pod 'JSONKit-NoWarning', '~> 1.2'
pod 'AFNetworking', '~> 2.4'
pod 'MBProgressHUD', '~> 0.9'
pod 'DCKeyValueObjectMapping', '~> 1.4'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'
pod 'Toast', '~> 2.3'
pod 'Facebook-iOS-SDK', '~> 3.17'
pod 'google-plus-ios-sdk', '~> 1.7'
pod 'SPChart', '~> 0.1'